[package]
name = "pion-core"

edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bumpalo       = { workspace = true }
ecow          = { workspace = true }
pion-interner = { workspace = true }
