[package]
name = "pion-lexer"

edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
text-size = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
